<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-7URID6Q" failures="1" tests="9" name="Test" time="0.454" errors="0" timestamp="2025-10-13T14:07:34 IST">
  <testcase classname="selenium.learning.java.testNG.Test1" name="failTest" time="0.036">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at selenium.learning.java.testNG.Test1.failTest(Test1.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase classname="selenium.learning.java.testNG.Test1" name="test1" time="0.004"/>
  <testcase classname="selenium.learning.java.testNG.Test1" name="test2" time="0.009"/>
  <testcase classname="selenium.learning.java.testNG.Test2" name="dataTest" time="0.002"/>
  <testcase classname="selenium.learning.java.testNG.Test2" name="dataTest" time="0.006"/>
  <testcase classname="selenium.learning.java.testNG.Test2" name="dataTest" time="0.009"/>
  <testcase classname="selenium.learning.java.testNG.Test2" name="test5" time="0.042"/>
  <testcase classname="selenium.learning.java.testNG.Test2" name="test4" time="0.002"/>
  <testcase classname="selenium.learning.java.testNG.Test2" name="test3" time="0.003"/>
  <testcase classname="selenium.learning.java.testNG.Test2" name="test6" time="0.0">
    <ignored/>
  </testcase> <!-- test6 -->
</testsuite> <!-- Test -->
